version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/gocham-service-web-react-typescript/build-dev # 배포될 위치
    overwrite: yes

permissions:
  - object: /usr/share/nginx/gocham-service-web-react-typescript/build-dev
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: ./deploy-dev.sh # ApplicationStart 단계에서 deploy.sh 실행
      timeout: 300
      runas: root
#      runas: ec2-user
